language: go

os:
  - linux
  - osx

go:
  - 1.6

install:
  - make dependencies
  - test -z "$(go fmt ./...)"
  - make

script: make test && make test-long && $GOPATH/bin/goveralls -service=travis-ci && make bench

sudo: false

branches:
  only:
    - master

notifications:
  email: false
